In [7]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

# Create an instance of the Chrome web driver
driver = webdriver.Chrome()

# Navigate to a website
driver.get("https://www.linkedin.com/login")
# User Credentials

In [8]:
user_name = 'datascrape42@gmail.com'
password1 = 'Scrape@123'

# Find the username and password fields and enter the login credentials
user = driver.find_element("id", "username")
user.send_keys(user_name)
password = driver.find_element("id", "password")
password.send_keys(password1)
# Click on the login button
log_in_button = driver.find_element("class name", "login__form_action_container")
log_in_button.click()

In [5]:
print("Select the Scrape")
print("1. Scrape Profiles")
print("2. Scrape jobs")
scrape = int(input("Enter your scrape \n"))

if scrape == 1:
  #choice which country to scrape
  print("Select the Country to scrape")
  print("1. India")
  print("2. USA")
  print("3. Lebanon")
  
  country=int(input("Enter your country \n"))
  if country == 3:
    #choice number of profiles to scrape
    print("Select the number of profiles to scrape")
    number_of_profiles=int(input("Enter the number of profiles to scrape \n"))
Links=[]
for page in range(2,5):
  
  try:
    # Navigate to a website
      driver.get("https://www.linkedin.com/search/results/PEOPLE/?geoUrn=%5B%22101834488%22%5D&origin=FACETED_SEARCH&page="+str(page)+"")
      time.sleep(3)
      ul = driver.find_element(By.XPATH, "//ul[@class='reusable-search__entity-result-list list-style-none']")
      li=ul.find_elements(By.TAG_NAME,"li")
      for i in li:
        link=i.find_element(By.TAG_NAME,"a")
        Links.append(link.get_attribute("href"))
  except:
    continue

Select the Scrape
1. Scrape Jobs
2. Scrape People
Select the Country to scrape
1. India
2. USA
3. Lebanon
Select the number of profiles to scrape

In [7]:
print(len(Links))
print(Links)

30
['https://www.linkedin.com/in/hiba-dawi-b98b5122a?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADl6hmQBQd6VK07_FOVDvqhrnkFYKMQ1HR4', 'https://www.linkedin.com/in/mario-hassrouty-10a882129?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAB-hhhoBuhh7Huwjyao6igopMQHNCQhifr4', 'https://www.linkedin.com/in/johnny-chreim?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADTJoXoBJwmYK-W7oiYnMaBhsdFIspVrUfo', 'https://www.linkedin.com/in/dalia-daou-93414a1b4?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADHa2LgB30G4S56I3GaGtQ4C4PZWnDxA468', 'https://www.linkedin.com/in/wael-fadel-2a3889217?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADbE1lsBvvHAYPFpSOLoH7tG-sNLLCLMRo0', 'https://www.linkedin.com/in/george-philippe-farajalla-1b9190a4?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABYYZh0BBHEFm5Ww8IiAzomCK0aqCYxCzGM', 'https://www.linkedin.com/in/derghamo?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAD0wMIUB8aL6Ql7qePL44emSJhrgdUMIXzA', 'https://www.linkedin.com/in/sami-mawass-s79119655?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACuJOOcB2Q2rrnW7_CVsBjwWO3Ejc_IK87E', 'https://www.linkedin.com/in/ivanbalhawan?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACwVmNgBwJYM6p5apqAh8dgMW9ZbTSlch0E', 'https://www.linkedin.com/in/jameel-zeidan-1259a8200?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADNnjK0B6glQHBVYtX4-rkFGfRKRiQtEAa4', 'https://www.linkedin.com/in/mohammed-almasry?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC-sI3YBq6BiVLSjIbonkYGHtvIgIFZBUUo', 'https://www.linkedin.com/in/ghiwa-al-ayash-889663140?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACJExykB-MbgI7OhGrRrLRIFDFxISeW3g2s', 'https://www.linkedin.com/in/zahraa-sweidan?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAB3YbBcBbPFRxlXkGVPaEMlhizkG_b_PwLA', 'https://www.linkedin.com/in/eva-el-mazboudi-aa98a2194?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC2xnaEBrF1nYN3ln0BD8_rg_SLBHfVbY6s', 'https://www.linkedin.com/in/hananhammoud?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC6MpmoBaapRVEy-l5DmiboGqlqkc9YHV1c', 'https://www.linkedin.com/in/rachelle-ghandour-mhrm-241b54a0?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABWG9VEBly36KHJlTCW-3dgZ0nU1Ma_vzDQ', 'https://www.linkedin.com/in/ali-daher2317?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADhtG3ABCAUCK_DCOkSrgTA5-3Sirkc2QJk', 'https://www.linkedin.com/in/hussein-chalhoub-218465184?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACt-ePQBpXskeIEryu4JUgdjUkRgosAOpOk', 'https://www.linkedin.com/in/lara-younis-b579258a?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABMAljMBUzw3R3SA-n7YZSvfiYGKRtKV-Ls', 'https://www.linkedin.com/in/carmen-harb-32337a208?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADS8YEsBTwn1Fr9cC0HtUsCgxRwmBr8e7Mo', 'https://www.linkedin.com/in/ahmad-altaweel-103a11b3?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABgtQFMBLZpypLiPmJ8CFOftjFXP53kFuww', 'https://www.linkedin.com/in/amani-daou-78aa741a2?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC9_7loBiPHrf006OYJFJe7Ga-aDE3fiyJA', 'https://www.linkedin.com/in/dania-kaakani-90368861?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAA0XmxMBuulyYJTihkRdfuiBbS7onggy1dE', 'https://www.linkedin.com/in/manal-naser-eddine-b90043117?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAB0EDtwBIYf176ZfvZDh5vtDH2N_aYm2cr0', 'https://www.linkedin.com/in/rawan-issa?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADHCbs8B54qIla7Jpb-efEtBSg9j7IWYlqM', 'https://www.linkedin.com/in/zainab-joumaa-631434183?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACtP8YUBtVTRlszDPzgqmt_0D3U_yjqc2hU', 'https://www.linkedin.com/in/sarkiskeloghlanian?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAB-_krQBMkWAPf7YQhKZfHAI1seK75w5JH0', 'https://www.linkedin.com/in/shahd-alabbar?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC1enFsB1rwYtyS-TRTA8BGuMuEwx9VitpM', 'https://www.linkedin.com/in/vanessa-khoury-068a64177?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACn7KVABR8JgzqXfiZgvv7f1G2G5BQ_HYN4', 'https://www.linkedin.com/in/farahwsaab?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAZTFrABybevrwg6o-0QvKMPyi0JX7pwEAY']

In [64]:
# driver.get("https://www.linkedin.com/in/ali-baydoun-33864923a/")
# time.sleep(3)
# find name and location and description through xpath using function and try and except


def find_name_location_description(driver=driver):
    try:
        name = driver.find_element(
            By.XPATH, "//h1[@class='text-heading-xlarge inline t-24 v-align-middle break-words']")
        location = driver.find_element(
            By.XPATH, "//span[@class='text-body-small inline t-black--light break-words']")
        description = driver.find_element(
            By.XPATH, "//div[@class='text-body-medium break-words']")
        return name.text, location.text, description.text
    except:
        return "No name, location or description found"

# find the current company through xpath using function and try and except


def find_current_company(driver=driver):
    try:
        company = []
        jobs = driver.find_element(
            By.CSS_SELECTOR, "ul.pv-text-details__right-panel")
        for job in jobs.find_elements(By.CSS_SELECTOR, "li"):
            company.append(job.text)
        return company
    except:
        return "No current company found"

# find the experience through xpath using function and try and except


def find_experience(driver=driver):  
    try:
        experianceList=[]
        experiance=driver.find_element("xpath","//div[@id='experience']")
#get parent
        parent=experiance.find_element(By.XPATH,"..")
        li=parent.find_elements(By.CSS_SELECTOR, 'ul li .display-flex.flex-row.justify-space-between ')
        for i in li:  
         experianceList.append(i.text.split("\n")[::2])
        return experianceList
    except:
        return "No experience found"

def find_about(driver=driver):
    try:
        about=driver.find_element("xpath","//div[@id='about']")
        # get parent
        parent = about.find_element(By.XPATH, "..")
        span=parent.find_elements(By.TAG_NAME,"span")[2]
        
        return span.text
    except:
        return "No about found"
# find the education through xpath using function and try and except
def find_education(driver=driver):
    try: 
        education = driver.find_element("xpath", "//div[@id='education']")
        # get parent
        parent = education.find_element(By.XPATH, "..")
        li = parent.find_elements(By.CSS_SELECTOR, 'ul li .display-flex.flex-row.justify-space-between ')
        educationList=[]
        for i in li:
            educationList.append(i.text.split("\n")[::2])
        return educationList
    except:
        return "No education found"
#find the skills through xpath using function and try and except
def find_skills(driver=driver):
    try:
        skillList=[]
        skills=driver.find_element("xpath","//div[@id='skills']")
        #get parent
        parent=skills.find_element(By.XPATH,"..")
        li=parent.find_elements(By.CSS_SELECTOR,'ul li .display-flex.flex-row.justify-space-between')
        for i in li:
            skillList.extend(i.text.split("\n")[::2])
        return skillList
    except:
        return " "
#if profile has experience
def have_experience(driver=driver):
    try:
        experiance=driver.find_element("xpath","//div[@id='experience']")
        return True
    except:
        return False
    
# find only university education through xpath using function and try and except
def find_university_education(driver=driver):
    try:
        educationList=[]
        education = driver.find_element("xpath", "//div[@id='education']")
        parent = education.find_element(By.XPATH, "..")
        li = parent.find_elements(By.CSS_SELECTOR, 'span')
        university=li[2].text.split("\n")[::2]
        try:
            degree=li[5].text.split("\n")[::2]
            educationList.append(university[0])
            educationList.append(degree[0])
            return educationList
        except:
            return educationList.append(university[0])
            
    except:
        return ""
                
#find the certifications through xpath using function and try and except
def find_certifications(driver=driver):
    try:
        certificationsList=[]
        licenses=driver.find_element("xpath","//div[@id='licenses_and_certifications']")
#get parent
        parent=licenses.find_element(By.XPATH,"..")
        li=parent.find_elements(By.CSS_SELECTOR,'ul li .display-flex.flex-row.justify-space-between')
        for i in li:
            certificationsList.extend(i.text.split("\n")[::2])
        return certificationsList
    except:
        return "No certifications found"
# company = find_current_company()
# name, location, description = find_name_location_description()
# experianceList = find_experience()
# educationList = find_education()
# skillList = find_skills()   
# about=find_about()
# certificationsList=find_certifications()

In [ ]:
# print("name is :",name)
# print("location is :",location)
# print("description is :",description)
# print("company is :",company)
# print("experianceList is :",experianceList)
# print("educationList is :",educationList)
# print("skillList is :",skillList)
# print("about is :",about)
# print("certificationsList is :",certificationsList)

:

In [63]:
driver.get("https://www.linkedin.com/in/derghamo/")
time.sleep(3)
#scroll down
listt=[]
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
education = driver.find_element("xpath", "//div[@id='education']")
# get parent
parent = education.find_element(By.XPATH, "..")
li = parent.find_elements(By.CSS_SELECTOR, 'span')
university=li[2].text.split("\n")[::2]
try:
  degree=li[5].text.split("\n")[::2]
  listt.append(university[0])
  listt.append(degree[0])
except:
  print( university[0])
  print("No Gpa found")
print(len(listt))

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='education']"}
  (Session info: chrome=113.0.5672.126)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x007C8893+48451]
	(No symbol) [0x0075B8A1]
	(No symbol) [0x00665058]
	(No symbol) [0x00690467]
	(No symbol) [0x0069069B]
	(No symbol) [0x006BDD92]
	(No symbol) [0x006AA304]
	(No symbol) [0x006BC482]
	(No symbol) [0x006AA0B6]
	(No symbol) [0x00687E08]
	(No symbol) [0x00688F2D]
	GetHandleVerifier [0x00A28E3A+2540266]
	GetHandleVerifier [0x00A68959+2801161]
	GetHandleVerifier [0x00A6295C+2776588]
	GetHandleVerifier [0x00852280+612144]
	(No symbol) [0x00764F6C]
	(No symbol) [0x007611D8]
	(No symbol) [0x007612BB]
	(No symbol) [0x00754857]
	BaseThreadInitThunk [0x77027D59+25]
	RtlInitializeExceptionChain [0x77A8B74B+107]
	RtlClearBits [0x77A8B6CF+191]

In [46]:
Links = ['https://www.linkedin.com/in/hiba-dawi-b98b5122a?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADl6hmQBQd6VK07_FOVDvqhrnkFYKMQ1HR4', 'https://www.linkedin.com/in/mario-hassrouty-10a882129?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAB-hhhoBuhh7Huwjyao6igopMQHNCQhifr4', 'https://www.linkedin.com/in/johnny-chreim?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADTJoXoBJwmYK-W7oiYnMaBhsdFIspVrUfo', 'https://www.linkedin.com/in/dalia-daou-93414a1b4?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADHa2LgB30G4S56I3GaGtQ4C4PZWnDxA468', 'https://www.linkedin.com/in/wael-fadel-2a3889217?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADbE1lsBvvHAYPFpSOLoH7tG-sNLLCLMRo0', 'https://www.linkedin.com/in/george-philippe-farajalla-1b9190a4?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABYYZh0BBHEFm5Ww8IiAzomCK0aqCYxCzGM', 'https://www.linkedin.com/in/derghamo?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAD0wMIUB8aL6Ql7qePL44emSJhrgdUMIXzA', 'https://www.linkedin.com/in/sami-mawass-s79119655?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACuJOOcB2Q2rrnW7_CVsBjwWO3Ejc_IK87E', 'https://www.linkedin.com/in/ivanbalhawan?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACwVmNgBwJYM6p5apqAh8dgMW9ZbTSlch0E', 'https://www.linkedin.com/in/jameel-zeidan-1259a8200?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADNnjK0B6glQHBVYtX4-rkFGfRKRiQtEAa4', 'https://www.linkedin.com/in/mohammed-almasry?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC-sI3YBq6BiVLSjIbonkYGHtvIgIFZBUUo', 'https://www.linkedin.com/in/ghiwa-al-ayash-889663140?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACJExykB-MbgI7OhGrRrLRIFDFxISeW3g2s', 'https://www.linkedin.com/in/zahraa-sweidan?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAB3YbBcBbPFRxlXkGVPaEMlhizkG_b_PwLA', 'https://www.linkedin.com/in/eva-el-mazboudi-aa98a2194?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC2xnaEBrF1nYN3ln0BD8_rg_SLBHfVbY6s', 'https://www.linkedin.com/in/hananhammoud?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC6MpmoBaapRVEy-l5DmiboGqlqkc9YHV1c',
         'https://www.linkedin.com/in/rachelle-ghandour-mhrm-241b54a0?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABWG9VEBly36KHJlTCW-3dgZ0nU1Ma_vzDQ', 'https://www.linkedin.com/in/ali-daher2317?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADhtG3ABCAUCK_DCOkSrgTA5-3Sirkc2QJk', 'https://www.linkedin.com/in/hussein-chalhoub-218465184?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACt-ePQBpXskeIEryu4JUgdjUkRgosAOpOk', 'https://www.linkedin.com/in/lara-younis-b579258a?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABMAljMBUzw3R3SA-n7YZSvfiYGKRtKV-Ls', 'https://www.linkedin.com/in/carmen-harb-32337a208?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADS8YEsBTwn1Fr9cC0HtUsCgxRwmBr8e7Mo', 'https://www.linkedin.com/in/ahmad-altaweel-103a11b3?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABgtQFMBLZpypLiPmJ8CFOftjFXP53kFuww', 'https://www.linkedin.com/in/amani-daou-78aa741a2?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC9_7loBiPHrf006OYJFJe7Ga-aDE3fiyJA', 'https://www.linkedin.com/in/dania-kaakani-90368861?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAA0XmxMBuulyYJTihkRdfuiBbS7onggy1dE', 'https://www.linkedin.com/in/manal-naser-eddine-b90043117?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAB0EDtwBIYf176ZfvZDh5vtDH2N_aYm2cr0', 'https://www.linkedin.com/in/rawan-issa?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADHCbs8B54qIla7Jpb-efEtBSg9j7IWYlqM', 'https://www.linkedin.com/in/zainab-joumaa-631434183?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACtP8YUBtVTRlszDPzgqmt_0D3U_yjqc2hU', 'https://www.linkedin.com/in/sarkiskeloghlanian?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAB-_krQBMkWAPf7YQhKZfHAI1seK75w5JH0', 'https://www.linkedin.com/in/shahd-alabbar?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAC1enFsB1rwYtyS-TRTA8BGuMuEwx9VitpM', 'https://www.linkedin.com/in/vanessa-khoury-068a64177?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAACn7KVABR8JgzqXfiZgvv7f1G2G5BQ_HYN4', 'https://www.linkedin.com/in/farahwsaab?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAAAZTFrABybevrwg6o-0QvKMPyi0JX7pwEAY']

In [66]:
info=[]

In [67]:
# get name,location,description,experiance,education,skills,licenses & certifications for all links and append to dectioanry
counter = len(info)+1
for i in range(0, 10):
    driver.get(Links[i])
    time.sleep(2)
    # company = find_current_company()
    name, location, description = find_name_location_description()
    about=find_about()
    have_exp=have_experience()
    university=find_university_education()
    skillsList = find_skills()
    # licensesList = find_certifications()
    # experianceList = find_experience()
    # educationList = find_education()

    print(counter)
    counter += 1
    print("-------------------")
    info.append({"name": name, "location": location, "description": description,"about":about,
                "experiance": have_exp, "university": university, "skills": skillsList})

    # info.append({"name":name,"location":location,"description":description,"company":company})

1
-------------------
2
-------------------
3
-------------------
4
-------------------
5
-------------------
6
-------------------
7
-------------------
8
-------------------
9
-------------------
10
-------------------

In [80]:
import pandas as pd
df=pd.DataFrame(info)
df.head()

,name,location,description,about,experiance,university,skills
0,Hiba Dawi,"Beirut Governorate, Lebanon",Data Scientist,No about found,True,"[Lebanese University, License Degree, Data Sci...",[IBM SPSS Statistics]
1,Mario Hassrouty,Lebanon,Data Engineer at CME,No about found,True,"[Notre Dame University - Louaize (NDU), Bachel...","[Microsoft Azure, SQL, C#]"
2,Johnny Chreim,"Beirut Governorate, Lebanon",🚀 Data Analyst 🚀,Becoming a successful Data Scientist and worki...,True,"[Lebanese University - Faculty of Information,...","[SQL, Python (Programming Language), Eclipse]"
3,Dalia daou,"Beirut Governorate, Lebanon",Software Engineer at CME,No about found,True,"[lebanese University faculty of technology , l...","[C#, Visual Basic .NET (VB.NET), SQL]"
4,Wael Fadel,Lebanon,Data Analyst | Business Intelligence Developer,"As a data analyst, I combine strong analytical...",True,"[Lebanese Canadian University - LCU, Bachelor'...","[Data Analysis, Business Intelligence (BI), SQL]"

In [81]:
def separate(df,colName):
  df = df.join(pd.DataFrame(df[colName].tolist()).add_prefix(colName))
  df.drop(colName, axis=1, inplace=True)
  return df



skills_seprate= separate(df,'skills')
education_seprate= separate(skills_seprate,'university')
education_seprate.head()
# education_seprate.to_csv('v4.csv', index=False)

,name,location,description,about,experiance,skills0,skills1,skills2,university0,university1
0,Hiba Dawi,"Beirut Governorate, Lebanon",Data Scientist,No about found,True,IBM SPSS Statistics,None,None,Lebanese University,"License Degree, Data Science"
1,Mario Hassrouty,Lebanon,Data Engineer at CME,No about found,True,Microsoft Azure,SQL,C#,Notre Dame University - Louaize (NDU),"Bachelor's degree, Computer Science"
2,Johnny Chreim,"Beirut Governorate, Lebanon",🚀 Data Analyst 🚀,Becoming a successful Data Scientist and worki...,True,SQL,Python (Programming Language),Eclipse,Lebanese University - Faculty of Information,"Bachelor's degree, Data Science"
3,Dalia daou,"Beirut Governorate, Lebanon",Software Engineer at CME,No about found,True,C#,Visual Basic .NET (VB.NET),SQL,lebanese University faculty of technology,lebanese University faculty of technology
4,Wael Fadel,Lebanon,Data Analyst | Business Intelligence Developer,"As a data analyst, I combine strong analytical...",True,Data Analysis,Business Intelligence (BI),SQL,Lebanese Canadian University - LCU,"Bachelor's degree, Finance, General"

In [82]:
# education_seprate['university1']
education_seprate[['degree', 'magor']] = education_seprate['university1'].str.split(',',1, expand=True)
education_seprate.drop('university1', axis=1, inplace=True)


# education_seprate.to_csv('v1.csv', index=False)

,name,location,description,about,experiance,skills0,skills1,skills2,university0,degree,magors
0,Hiba Dawi,"Beirut Governorate, Lebanon",Data Scientist,No about found,True,IBM SPSS Statistics,None,None,Lebanese University,License Degree,Data Science
1,Mario Hassrouty,Lebanon,Data Engineer at CME,No about found,True,Microsoft Azure,SQL,C#,Notre Dame University - Louaize (NDU),Bachelor's degree,Computer Science
2,Johnny Chreim,"Beirut Governorate, Lebanon",🚀 Data Analyst 🚀,Becoming a successful Data Scientist and worki...,True,SQL,Python (Programming Language),Eclipse,Lebanese University - Faculty of Information,Bachelor's degree,Data Science
3,Dalia daou,"Beirut Governorate, Lebanon",Software Engineer at CME,No about found,True,C#,Visual Basic .NET (VB.NET),SQL,lebanese University faculty of technology,lebanese University faculty of technology,None
4,Wael Fadel,Lebanon,Data Analyst | Business Intelligence Developer,"As a data analyst, I combine strong analytical...",True,Data Analysis,Business Intelligence (BI),SQL,Lebanese Canadian University - LCU,Bachelor's degree,"Finance, General"

In [88]:
# education_seprate['description'].str.contains('Data Analyst')


education_seprate.loc[education_seprate['description'].str.contains('Data Analyst '), 'description'] = 'Data Analyst'
education_seprate.loc[education_seprate['description'].str.contains('Data Engineer '), 'description'] = 'Data Engineer'
education_seprate.loc[education_seprate['description'].str.contains('Data Scientist '), 'description'] = 'Data Scientist'
education_seprate.loc[education_seprate['description'].str.contains('Software'), 'description'] = 'Software Engineer'


# education_seprate['description'].replace(['Data Analyst'], 'Data Analyst', inplace=True)

education_seprate.head()
education_seprate.to_csv('end.csv', index=False)

In [83]:
education_seprate.to_csv('endVersion2.csv', index=False)